## Importing necessary libraries

In [127]:
import numpy as np
import pandas as pd
import matplotlib as plt
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Loading Datasets

In [128]:
#loading the datasets

flight = pd.read_csv("/content/drive/MyDrive/Data-Mining/flights.csv")
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z

In [129]:
plane_data = pd.read_csv("/content/drive/MyDrive/Data-Mining/plane-data.csv")
plane_data.head()

,tailnum,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year
0,N050AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N051AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N052AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N054AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N055AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
flight_routes = pd.read_csv("/content/drive/MyDrive/Data-Mining/us_flight_routes.csv", encoding ="utf-16",delimiter='\t')
flight_routes.tail()

,Airport ID,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Buffer,Destination Airport ID,Destination Latitude,Destination Longitude,Destination Point,Distance (Miles),Makeline,Number of Airlines,Origin Airport ID,Origin Latitude,Origin Longitude,Origin Point
4959,3469,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,False,SFO,San Francisco,United States,San Francisco International Airport,Polygon,3682,33.6367,-84.428101,Point,2138.896563,LineString,11,3469,37.618999,-122.375000,Point
4960,3682,MIA,Miami,United States,Miami International Airport,True,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,Polygon,3576,25.7932,-80.290604,Point,594.601524,LineString,12,3682,33.636700,-84.428101,Point
4961,3576,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,MIA,Miami,United States,Miami International Airport,Polygon,3682,33.6367,-84.428101,Point,594.601524,LineString,12,3576,25.793200,-80.290604,Point
4962,3682,ORD,Chicago,United States,Chicago O'Hare International Airport,True,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,Polygon,3830,41.9786,-87.904800,Point,605.810275,LineString,19,3682,33.636700,-84.428101,Point
4963,3830,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,ORD,Chicago,United States,Chicago O'Hare International Airport,Polygon,3682,33.6367,-84.428101,Point,605.810275,LineString,20,3830,41.978600,-87.904800,Point

## Checking number of Categorical and Numerical Attributes

In [131]:
flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

In [169]:
plane_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5029 entries, 0 to 5028
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tailnum        5029 non-null   object
 1   type           4480 non-null   object
 2   manufacturer   4480 non-null   object
 3   issue_date     4479 non-null   object
 4   model          4480 non-null   object
 5   status         4480 non-null   object
 6   aircraft_type  4480 non-null   object
 7   engine_type    4477 non-null   object
 8   year           4335 non-null   float64
dtypes: float64(1), object(8)
memory usage: 353.7+ KB

In [170]:
flight_routes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4964 entries, 0 to 4963
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Airport ID              4964 non-null   int64
 1   Destination Airport     4964 non-null   object
 2   Destination City        4964 non-null   object
 3   Destination Country     4964 non-null   object
 4   Destination Name        4964 non-null   object
 5   Distance                4964 non-null   bool
 6   Origin Airport          4964 non-null   object
 7   Origin City             4964 non-null   object
 8   Origin Country          4964 non-null   object
 9   Origin Name             4964 non-null   object
 10  Buffer                  4964 non-null   object
 11  Destination Airport ID  4964 non-null   int64
 12  Destination Latitude    4964 non-null   float64
 13  Destination Longitude   4964 non-null   float64
 14  Destination Point       4964 non-null   object
 15  Distance (Miles)        4964 non-null   float64
 16  Makeline                4964 non-null   object
 17  Number of Airlines      4964 non-null   int64
 18  Origin Airport ID       4964 non-null   int64
 19  Origin Latitude         4964 non-null   float64
 20  Origin Longitude        4964 non-null   float64
 21  Origin Point            4964 non-null   object
dtypes: bool(1), float64(5), int64(4), object(12)
memory usage: 819.4+ KB

## Checking number of missing values in each dataframe

In [132]:
flight.isna().sum()

year                 0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8713
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [133]:
plane_data.isna().sum()

tailnum            0
type             549
manufacturer     549
issue_date       550
model            549
status           549
aircraft_type    549
engine_type      552
year             694
dtype: int64

In [134]:
flight_routes.isna().sum()

Airport ID                0
Destination Airport       0
Destination City          0
Destination Country       0
Destination Name          0
Distance                  0
Origin Airport            0
Origin City               0
Origin Country            0
Origin Name               0
Buffer                    0
Destination Airport ID    0
Destination Latitude      0
Destination Longitude     0
Destination Point         0
Distance (Miles)          0
Makeline                  0
Number of Airlines        0
Origin Airport ID         0
Origin Latitude           0
Origin Longitude          0
Origin Point              0
dtype: int64

## Checking number of rows in each table.

In [135]:
len(flight)

336776

In [136]:
len(plane_data)

5029

In [137]:
len(flight_routes)

4964

## Replacing missing values, and carrying out Data Transformation

Replacing the missing values `dep_time` and `arr_time` with `sched_dep_time` and `sched_arr_time` as we are assuming that if there was no actual departure and arrival time, then the plane departed and arrived as per schedule.

In [171]:
# Replace missing values in dep_time with sched_dep_time
flight.loc[flight['dep_time'].isna(), 'dep_time'] = flight['sched_dep_time']

# Replace missing values in arr_time with sched_arr_time
flight.loc[flight['arr_time'].isna(), 'arr_time'] = flight['sched_arr_time']

flight.isna().sum()

year                 0
month                0
day                  0
dep_time             0
sched_dep_time       0
dep_delay            0
arr_time             0
sched_arr_time       0
arr_delay            0
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time             0
distance             0
hour                 0
minute               0
dtype: int64

Now that we have all the values in `dep_time` and `arr_time`, we can replace the missing values in `dep_delay` and `arr_delay` by subtracting the actual times with the schedule times.

In [139]:
import pandas as pd

# Function to convert HHMM format to total minutes
def convert_to_minutes(time_col):
    # Handle NaN cases for dep_time (since it's float64, it could have NaNs)
    time_col = time_col.fillna(0).astype(int)

    # Extract hours and minutes from HHMM format
    hours = time_col // 100
    minutes = time_col % 100

    # Convert the time into total minutes
    return hours * 60 + minutes

# Convert dep_time and sched_dep_time to minutes
flight['dep_time_minutes'] = convert_to_minutes(flight['dep_time'])
flight['sched_dep_time_minutes'] = convert_to_minutes(flight['sched_dep_time'])

# Replace missing dep_delay values by calculating dep_time - sched_dep_time
flight.loc[flight['dep_delay'].isna(), 'dep_delay'] = flight['dep_time_minutes'] - flight['sched_dep_time_minutes']

# Convert arr_time and sched_arr_time to minutes
flight['arr_time_minutes'] = convert_to_minutes(flight['arr_time'])
flight['sched_arr_time_minutes'] = convert_to_minutes(flight['sched_arr_time'])

# Replace missing arr_delay values by calculating arr_time - sched_arr_time
flight.loc[flight['arr_delay'].isna(), 'arr_delay'] = flight['arr_time_minutes'] - flight['sched_arr_time_minutes']

# Drop the intermediate time columns if no longer needed
flight = flight.drop(columns=['dep_time_minutes', 'sched_dep_time_minutes', 'arr_time_minutes', 'sched_arr_time_minutes'])

# Display the updated flight dataframe
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z

In [140]:
flight.isna().sum()

year                 0
month                0
day                  0
dep_time             0
sched_dep_time       0
dep_delay            0
arr_time             0
sched_arr_time       0
arr_delay            0
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

Replacing the missing values in `air_time` as well by subtracting `arr_time` with `dep_time`

In [141]:
flight['arr_time_minutes'] = convert_to_minutes(flight['arr_time'])
flight['dep_time_minutes'] = convert_to_minutes(flight['dep_time'])

# Replace missing air_time values by calculating arr_time - dep_time
flight.loc[flight['air_time'].isna(), 'air_time'] = flight['arr_time_minutes'] - flight['dep_time_minutes']

# If you need to handle cases where the flight crosses midnight (e.g., dep_time is 2300 and arr_time is 0100):
flight.loc[flight['air_time'] < 0, 'air_time'] += 24 * 60  # Add 24 hours in minutes to fix negative values

# Drop the intermediate time columns if no longer needed
flight = flight.drop(columns=['arr_time_minutes', 'dep_time_minutes'])

# Display the updated flight dataframe
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z

In [142]:
flight.isna().sum()

year                 0
month                0
day                  0
dep_time             0
sched_dep_time       0
dep_delay            0
arr_time             0
sched_arr_time       0
arr_delay            0
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time             0
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

Removing the `time_hour` column as it is not required

In [143]:
# Remove the 'time_hour' column from the flight dataframe
flight = flight.drop(columns=['time_hour'])

# Display the updated flight dataframe
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0

## Merging 2 datasets together.

merging `flight` and `plane_data` using left join on `tailnum` column to create a new `merged_data`.

In [144]:
# Perform left join on a common key, e.g., 'plane_id'
# Replace 'plane_id' with the actual column name common to both datasets
merged_data = pd.merge(flight, plane_data, how='left', on='tailnum')

# Display the first few rows of the merged dataset
merged_data.head()

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0

In [145]:
merged_data.isna().sum()

year_x                 0
month                  0
day                    0
dep_time               0
sched_dep_time         0
dep_delay              0
arr_time               0
sched_arr_time         0
arr_delay              0
carrier                0
flight                 0
tailnum             2512
origin                 0
dest                   0
air_time               0
distance               0
hour                   0
minute                 0
type              113992
manufacturer      113992
issue_date        114010
model             113992
status            113992
aircraft_type     113992
engine_type       113992
year_y            119780
dtype: int64

In [146]:
len(merged_data)

336776

We will replace the missing values in the new columns of `merged_data` with "Not Available" because we cannot really replace these values with anything. We cannot make up these values. Hence its best suited to just replace them with saying that the data was not available.

"Not Available" - This will show that there are no missing values and you also don't have to loose any data points (in this case, any flights). When creating visualizations using these columns with "Not Available" values, we will just ignore the Not Available values.

In [147]:
# List of columns where missing values should be replaced with 'Not Available'
columns_to_fill = ['tailnum', 'type', 'manufacturer', 'issue_date', 'model', 'status', 'aircraft_type', 'engine_type', 'year_y']

# Replace missing values in these columns with 'Not Available'
merged_data[columns_to_fill] = merged_data[columns_to_fill].fillna("Not Available")

# Display the updated plane_data dataframe
merged_data.isna().sum()

year_x            0
month             0
day               0
dep_time          0
sched_dep_time    0
dep_delay         0
arr_time          0
sched_arr_time    0
arr_delay         0
carrier           0
flight            0
tailnum           0
origin            0
dest              0
air_time          0
distance          0
hour              0
minute            0
type              0
manufacturer      0
issue_date        0
model             0
status            0
aircraft_type     0
engine_type       0
year_y            0
dtype: int64

In [148]:
flight_routes.columns

Index(['Airport ID', 'Destination Airport', 'Destination City',
       'Destination Country', 'Destination Name', 'Distance', 'Origin Airport',
       'Origin City', 'Origin Country', 'Origin Name', 'Buffer',
       'Destination Airport ID', 'Destination Latitude',
       'Destination Longitude', 'Destination Point ', 'Distance (Miles)',
       'Makeline', 'Number of Airlines', 'Origin Airport ID',
       'Origin Latitude', 'Origin Longitude', 'Origin Point'],
      dtype='object')

In [149]:
merged_data.columns

Index(['year_x', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'type', 'manufacturer', 'issue_date', 'model', 'status',
       'aircraft_type', 'engine_type', 'year_y'],
      dtype='object')

## Merging the 3rd Dataset.

Combining `merged_data` and `flight_routes` on `origin` and `dest`. This will give us information of Origina airport, Destination airports, Origin City, Destination City and other Route Information.

In [150]:
# Merge the two datasets on origin and destination airport codes
combined_data = pd.merge(merged_data, flight_routes,
                         how='left',
                         left_on=['origin', 'dest'],
                         right_on=['Origin Airport', 'Destination Airport'])

# Display the first few rows of the combined dataset
combined_data.head()

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Airport ID,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Buffer,Destination Airport ID,Destination Latitude,Destination Longitude,Destination Point,Distance (Miles),Makeline,Number of Airlines,Origin Airport ID,Origin Latitude,Origin Longitude,Origin Point
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3494.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3550.0,29.9844,-95.341400,Point,1399.812458,LineString,1.0,3494.0,40.692501,-74.168701,Point
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,3697.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,Polygon,3550.0,29.9844,-95.341400,Point,1416.367401,LineString,2.0,3697.0,40.777199,-73.872597,Point
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,3797.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,Polygon,3576.0,25.7932,-80.290604,Point,1089.635644,LineString,3.0,3797.0,40.639801,-73.778900,Point
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,3697.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3682.0,33.6367,-84.428101,Point,761.521651,LineString,7.0,3697.0,40.777199,-73.872597,Point

In [151]:
# Set display options to show all columns
pd.set_option('display.max_columns', None)

# Now, when you display the DataFrame, it will show all columns
combined_data.head(10)

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Airport ID,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Buffer,Destination Airport ID,Destination Latitude,Destination Longitude,Destination Point,Distance (Miles),Makeline,Number of Airlines,Origin Airport ID,Origin Latitude,Origin Longitude,Origin Point
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3494.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3550.0,29.984400,-95.341400,Point,1399.812458,LineString,1.0,3494.0,40.692501,-74.168701,Point
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,3697.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,Polygon,3550.0,29.984400,-95.341400,Point,1416.367401,LineString,2.0,3697.0,40.777199,-73.872597,Point
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,3797.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,Polygon,3576.0,25.793200,-80.290604,Point,1089.635644,LineString,3.0,3797.0,40.639801,-73.778900,Point
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,3697.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3682.0,33.636700,-84.428101,Point,761.521651,LineString,7.0,3697.0,40.777199,-73.872597,Point
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3494.0,ORD,Chicago,United States,Chicago O'Hare International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3830.0,41.978600,-87.904800,Point,719.156918,LineString,3.0,3494.0,40.692501,-74.168701,Point
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,Foreign Corporation,AIRBUS INDUSTRIE,10/05/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,3494.0,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3533.0,26.072599,-80.152702,Point,1064.607704,LineString,2.0,3494.0,40.692501,-74.168701,Point
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,Corporation,CANADAIR,04/23/2004,CL-600-2B19,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,3697.0,IAD,Washington,United States,Washington Dulles International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3714.0,38.944500,-77.455803,Point,228.624105,LineString,1.0,3697.0,40.777199,-73.872597,Point
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,Corporation,AIRBUS,09/29/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,3797.0,MCO,Orlando,United States,Orlando International Airport,True,JFK,New York,United States,John F Kennedy International Airport,Polygon,3878.0,28.429399,-81.308998,Point,944.001760,LineString,4.0,3797.0,40.639801,-73.778900,Point
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3697.0,ORD,Chicago,United States,Chicago O'Hare International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3830.0,41.978600,-87.904800,Point,733.245012,LineString,5.0,3697.0,40.777199,-73.872597,Point

In [152]:
combined_data.columns

Index(['year_x', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'type', 'manufacturer', 'issue_date', 'model', 'status',
       'aircraft_type', 'engine_type', 'year_y', 'Airport ID',
       'Destination Airport', 'Destination City', 'Destination Country',
       'Destination Name', 'Distance', 'Origin Airport', 'Origin City',
       'Origin Country', 'Origin Name', 'Buffer', 'Destination Airport ID',
       'Destination Latitude', 'Destination Longitude', 'Destination Point ',
       'Distance (Miles)', 'Makeline', 'Number of Airlines',
       'Origin Airport ID', 'Origin Latitude', 'Origin Longitude',
       'Origin Point'],
      dtype='object')

Removing unncessary columns that won't be required for analysis.

In [153]:
# Remove the 'time_hour' column from the flight dataframe
combined_data = combined_data.drop(columns=['Buffer','Makeline','Origin Latitude','Origin Longitude','Origin Point','Destination Airport ID',
                                            'Destination Latitude', 'Destination Longitude','Destination Point ','Origin Point',
                                            'Origin Point','Distance (Miles)','Origin Airport ID','Airport ID'])

# Display the updated flight dataframe
combined_data.head(55)

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Number of Airlines
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,1.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,2.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,3.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,7.0
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,3.0
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,Foreign Corporation,AIRBUS INDUSTRIE,10/05/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,Corporation,CANADAIR,04/23/2004,CL-600-2B19,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,IAD,Washington,United States,Washington Dulles International Airport,True,LGA,New York,United States,La Guardia Airport,1.0
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,Corporation,AIRBUS,09/29/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,MCO,Orlando,United States,Orlando International Airport,True,JFK,New York,United States,John F Kennedy International Airport,4.0
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,LGA,New York,United States,La Guardia Airport,5.0
10,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,PBI,West Palm Beach,United States,Palm Beach International Airport,False,JFK,New York,United States,John F Kennedy International Airport,1.0
11,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,Corporation,AIRBUS,05/04/2007,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2007.0,TPA,Tampa,United States,Tampa International Airport,False,JFK,New York,United States,John F Kennedy International Airport,4.0
12,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,Corporation,BOEING,03/27/1998,757-224,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,LAX,Los Angeles,United States,Los Angeles International Airport,False,JFK,New York,United States,John F Kennedy International Airport,8.0
13,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,SFO,San Francisco,United States,San Francisco International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
14,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,DFW,Dallas-Fort Worth,United States,Dallas Fort Worth International Airport,False,LGA,New York,United States,La Guardia Airport,4.0
15,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,BOS,Boston,United States,General Edward Lawrence Logan International Ai...,True,JFK,New York,United States,John F Kennedy International Airport,4.0
16,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,LAS,Las Vegas,United States,McCarran International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,1.0
17,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,Corporation,AIRBUS,10/14/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,LGA,New York,United States,La Guardia Airport,3.0
18,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,7.0
19,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,Corporation,AIRBUS,09/20/2006,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2006.0,PBI,West Palm Beach,United States,Palm Beach International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
20,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,Corporation,MCDONNELL DOUGLAS AIRCRAFT CO,06/27/1991,MD-88,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1991.0,MSP,Minneapolis,United States,Minneapolis-St Paul International/Wold-Chamber...,False,LGA,New York,United States,La Guardia Airport,1.0
21,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,DTW,Detroit,United States,Detroit Metropolitan Wayne County Airport,True,LGA,New York,United States,La Guardia Airport,4.0
22,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,Corporation,BOEING,11/16/1990,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,MIA,Miami,United States,Miami International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,3.0
23,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,JFK,New York,United States,John F Kennedy International Airport,7.0
24,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,MIA,Miami,United States,Miami International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,3.0
25,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,3.0
26,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,Corporation,BOEING,06/21/1991,757-222,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,SFO,San Francisco,United States,San Francisco International Airport,False,JFK,New York,United States,John F Kennedy International Airport,7.0
27,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,Corporation,AIRBUS,04/04/2006,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2006.0,RSW,Fort Myers,United States,Southwest Florida International Airport,False,JFK,New York,United States,John F Kennedy International Airport,1.0
28,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,Corporation,AIRBUS INDUSTRIE,05/22/2001,A319-114,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2001.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,7.0
30,2013,1,1,622.0,630,-8.0,1017.0,1014,3.0,US,245,N807AW,EWR,PHX,342.0,2133,6,30,Corporation,AIRBUS INDUSTRIE,10/28/2004,A319-132,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1999.0,PHX,Phoenix,United States,Phoenix Sky Harbor International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,4.0
31,2013,1,1,623.0,610,13.0,920.0,915,5.0,AA,1837,N3EMAA,LGA,MIA,153.0,1096,6,10,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,MIA,Miami,United States,Miami International Airport,False,LGA,New York,United States,La Guardia Airport,3.0
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,Corporation,AIRBUS INDUSTRIE,04/13/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,2.0
33,2013,1,1,624.0,630,-6.0,909.0,840,29.0,EV,4626,N11107,EWR,MSP,190.0,1008,6,30,Corporation,EMBRAER,06/25/2003,EMB-145XR,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2002.0,MSP,Minneapolis,United States,Minneapolis-St Paul International/Wold-Chamber...,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
34,2013,1,1,624.0,630,-6.0,840.0,830,10.0,MQ,4599,N518MQ,LGA,MSP,166.0,1020,6,30,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,MSP,Minneapolis,United States,Minneapolis-St Paul International/Wold-Chamber...,False,LGA,New York,United States,La Guardia Airport,1.0
35,2013,1,1,627.0,630,-3.0,1018.0,1018,0.0,US,27,N535UW,JFK,PHX,330.0,2153,6,30,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,PHX,Phoenix,United States,Phoenix Sky Harbor International Airport,False,JFK,New York,United States,John F Kennedy International Airport,4.0
36,2013,1,1,628.0,630,-2.0,1137.0,1140,-3.0,AA,413,N3BAAA,JFK,SJU,192.0,1598,6,30,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2013,1,1,628.0,630,-2.0,1016.0,947,29.0,UA,1665,N33289,EWR,LAX,366.0,2454,6,30,Corporation,BOEING,07/30/2004,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,LAX,Los Angeles,United States,Los Angeles International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
38,2013,1,1,629.0,630,-1.0,824.0,810,14.0,AA,303,N3CYAA,LGA,ORD,140.0,733,6,30,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,LGA,New York,United States,La Guardia Airport,5.0
39,2013,1,1,629.0,630,-1.0,721.0,740,-19.0,WN,4646,N273WN,LGA,BWI,40.0,185,6,30,Corporation,BOEING,05/07/2007,737-7H4,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2007.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2013,1,1,629.0,630,-1.0,824.0,833,-9.0,US,1019,N426US,EWR,CLT,91.0,529,6,30,Corporation,BOEING,12/03/2003,737-4B7,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1989.0,CLT,Charlotte,United States,Charlotte Douglas International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,3.0
41,2013,1,1,632.0,608,24.0,740.0,728,12.0,EV,4144,N13553,EWR,IAD,52.0,212,6,8,Corporation,EMBRAER,05/30/2002,EMB-145LR,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2002.0,IAD,Washington,United States,Washington Dulles International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,1.0
42,2013,1,1,635.0,635,0.0,1028.0,940,48.0,AA,711,N3GKAA,LGA,DFW,248.0,1389,6,35,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,DFW,Dallas-Fort Worth,United States,Dallas Fort Worth International Airport,False,LGA,New York,United States,La Guardia Airport,4.0
43,2013,1,1,637.0,645,-8.0,930.0,935,-5.0,B6,389,N709JB,LGA,MCO,144.0,950,6,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,MCO,Orlando,United States,Orlando International Airport,True,LGA,New York,United States,La Guardia Airport,2.0
44,2013,1,1,639.0,640,-1.0,739.0,749,-10.0,B6,1002,N805JB,JFK,BOS,41.0,187,6,40,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,BOS,Boston,United States,General Edward Lawrence Logan International Ai...,True,JFK,New York,United States,John F Kennedy International Airport,4.0
45,2013,1,1,643.0,646,-3.0,922.0,940,-18.0,UA,556,N497UA,EWR,PBI,146.0,1023,6,46,Corporation,AIRBUS,09/18/2002,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2002.0,PBI,West Palm Beach,United States,Palm Beach International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
46,2013,1,1,643.0,645,-2.0,837.0,848,-11.0,US,926,N178US,EWR,CLT,91.0,529,6,45,Corporation,AIRBUS INDUSTRIE,06/14/2001,A321-211,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2001.0,CLT,Charlotte,United States,Charlotte Douglas International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,3.0
47,2013,1,1,644.0,636,8.0,931.0,940,-9.0,UA,1701,N75435,EWR,FLL,151.0,1065,6,36,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
48,2013,1,1,645.0,647,-2.0,815.0,810,5.0,B6,102,N796JB,JFK,BUF,63.0,301,6,47,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,BUF,Buffalo,United States,Buffalo Niagara International Airport,True,JFK,New York,United States,John F Kennedy International Airport,2.0
49,2013,1,1,646.0,645,1.0,910.0,916,-6.0,UA,883,N569UA,LGA,DEN,243.0,1620,6,45,Corporation,BOEING,07/26/2006,757-222,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1992.0,DEN,Denver,United States,Denver International Airport,False,LGA,New York,United States,La Guardia Airport,4.0
50,2013,1,1,646.0,645,1.0,1023.0,1030,-7.0,UA,1496,N38727,EWR,SNA,380.0,2434,6,45,Corporation,BOEING,07/14/1999,737-724,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1999.0,SNA,Santa Ana,United States,John Wayne Airport-Orange County Airport,False,EWR,Newark,United States,Newark Liberty International Airport,1.0
51,2013,1,1,651.0,655,-4.0,936.0,942,-6.0,B6,203,N558JB,JFK,LAS,323.0,2248,6,55,Corporation,AIRBUS,01/29/2003,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2003.0,LAS,Las Vegas,United States,McCarran International Airport,False,JFK,New York,United States,John F Kennedy International Airport,8.0
52,2013,1,1,652.0,655,-3.0,932.0,921,11.0,B6,117,N178JB,JFK,MSY,191.0,1182,6,55,Corporation,EMBRAER,12/19/2005,ERJ 190-100 IGW,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2005.0,MSY,New Orleans,United States,Louis Armstrong New Orleans International Airport,False,JFK,New York,United States,John F Kennedy International Airport,11.0
53,2013,1,1,653.0,700,-7.0,936.0,1009,-33.0,DL,1383,N327NW,LGA,PBI,149.0,1035,7,0,Corporation,AIRBUS INDUSTRIE,04/01/1992,A320-211,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1992.0,PBI,West Palm Beach,United States,Palm Beach International Airport,False,LGA,New York,United States,La Guardia Airport,4.0
54,2013,1,1,655.0,655,0.0,1021.0,1030,-9.0,DL,1415,N3763D,JFK,SLC,294.0,1990,6,55,Corporation,BOEING,12/20/2001,737-832,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2001.0,SLC,Salt Lake City,United States,Salt Lake City International Airport,False,JFK,New York,United States,John F Kennedy International Airport,2.0

In [154]:
combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport    10948
Destination City       10948
Destination Country    10948
Destination Name       10948
Distance               10948
Origin Airport         10948
Origin City            10948
Origin Country         10948
Origin Name            10948
Number of Airlines     10948
dtype: int64

Let's find out the what are the destination airports that are having missing values for the particular `dest` in our flights.

In [155]:
# Filter rows where 'Destination City' has missing values (NaN)
missing_destination_city = combined_data[combined_data['Destination City'].isna()]

# Get the value counts of 'dest' for those rows
dest_value_counts = missing_destination_city['dest'].value_counts()

dest_value_counts

dest
SJU    5819
BQN     896
HNL     707
STT     522
BDL     443
PSE     365
MCI     276
AVL     275
IAH     274
ACK     265
MVY     221
EGE     213
MKE     183
CRW     138
CAE     104
TVC     101
BZN      36
JAC      25
PSP      19
HDN      15
MTJ      15
BWI      15
SBN      10
ANC       8
MEM       1
BHM       1
LGA       1
Name: count, dtype: int64

Doing the same for Origin as well.

In [156]:
# Filter rows where 'Destination City' has missing values (NaN)
missing_origin_city = combined_data[combined_data['Origin City'].isna()]

# Get the value counts of 'dest' for those rows
missing_origin_counts = missing_destination_city['origin'].value_counts()

missing_origin_counts

origin
JFK    7736
EWR    2966
LGA     246
Name: count, dtype: int64

To manually replace the missing values in the `Destination City` and `Destination Country` column based on the `dest` codes and their corresponding cities, we can create a mapping between dest and Destination City, and then apply this mapping to fill the missing values.

In [157]:
# Create a mapping dictionary for 'dest' to 'Destination City'
city_mapping = {
    'SJU': 'Carolina',
    'BQN': 'Aguadilla',
    'HNL': 'Honolulu',
    'STT': 'St. Thomas',
    'BDL': 'Windsor Locks',
    'PSE': 'Ponce',
    'MCI': 'Missouri',
    'AVL': 'Fletcher',
    'IAH': 'Houston',
    'ACK': 'Nantucket',
    'MVY': 'West Tisbury',
    'EGE': 'Eagle County',
    'MKE': 'Milwaukee',
    'CRW': 'Charleston',
    'CAE': 'West Columbia',
    'TVC': 'Traverse City',
    'BZN': 'Bozeman',
    'JAC': 'Jackson',
    'PSP': 'Palm Springs',
    'HDN': 'Hayden',
    'MTJ': 'Montrose',
    'BWI': 'Baltimore',
    'SBN': 'South Bend',
    'ANC': 'Anchorage',
    'MEM': 'Memphis',
    'BHM': 'Birmingham',
    'LGA': 'LaGuardia'
}

# Create a mapping dictionary for 'dest' to 'Destination Country'
country_mapping = {
    'SJU': 'Puerto Rico',
    'BQN': 'Puerto Rico',
    'HNL': 'Hawaii',
    'STT': 'US Virgin Islands',
    'BDL': 'United States',
    'PSE': 'Puerto Rico',
    'MCI': 'United States',
    'AVL': 'United States',
    'IAH': 'United States',
    'ACK': 'United States',
    'MVY': 'United States',
    'EGE': 'United States',
    'MKE': 'United States',
    'CRW': 'United States',
    'CAE': 'United States',
    'TVC': 'United States',
    'BZN': 'United States',
    'JAC': 'United States',
    'PSP': 'United States',
    'HDN': 'United States',
    'MTJ': 'United States',
    'BWI': 'United States',
    'SBN': 'United States',
    'ANC': 'United States',
    'MEM': 'United States',
    'BHM': 'United States',
    'LGA': 'United States'
}

# Replace missing values in 'Destination City' using the city_mapping
combined_data['Destination City'] = combined_data['Destination City'].fillna(combined_data['dest'].map(city_mapping))

# Replace missing values in 'Destination Country' using the country_mapping
combined_data['Destination Country'] = combined_data['Destination Country'].fillna(combined_data['dest'].map(country_mapping))

# Display the updated combined_data dataframe
combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport    10948
Destination City           0
Destination Country        0
Destination Name       10948
Distance               10948
Origin Airport         10948
Origin City            10948
Origin Country         10948
Origin Name            10948
Number of Airlines     10948
dtype: int64

Doing the same for Origin City and Origin Country with origin

In [158]:
# Create a mapping dictionary for 'origin' to 'Origin City'
origin_city_mapping = {
    'JFK': 'New York',
    'EWR': 'Newark',
    'LGA': 'LaGuardia'
}

# Create a mapping dictionary for 'origin' to 'Origin Country'
origin_country_mapping = {
    'JFK': 'United States',
    'EWR': 'United States',
    'LGA': 'United States'
}

# Replace missing values in 'Origin City' using the origin_city_mapping
combined_data['Origin City'] = combined_data['Origin City'].fillna(combined_data['origin'].map(origin_city_mapping))

# Replace missing values in 'Origin Country' using the origin_country_mapping
combined_data['Origin Country'] = combined_data['Origin Country'].fillna(combined_data['origin'].map(origin_country_mapping))

combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport    10948
Destination City           0
Destination Country        0
Destination Name       10948
Distance               10948
Origin Airport         10948
Origin City                0
Origin Country             0
Origin Name            10948
Number of Airlines     10948
dtype: int64

Creating mappings for Desitnation Name and Origin Name as well.

In [159]:
# Create a mapping dictionary for 'dest' to 'Destination Name' (airport names)
destination_name_mapping = {
    'SJU': 'Luis Muñoz Marín International Airport',
    'BQN': 'Rafael Hernández Airport',
    'HNL': 'Daniel K. Inouye International Airport',
    'STT': 'Cyril E. King Airport',
    'BDL': 'Bradley International Airport',
    'PSE': 'Mercedita International Airport',
    'MCI': 'Kansas City International Airport',
    'AVL': 'Asheville Regional Airport',
    'IAH': 'George Bush Intercontinental Airport',
    'ACK': 'Nantucket Memorial Airport',
    'MVY': 'Martha\'s Vineyard Airport',
    'EGE': 'Eagle County Regional Airport',
    'MKE': 'General Mitchell International Airport',
    'CRW': 'Yeager Airport',
    'CAE': 'Columbia Metropolitan Airport',
    'TVC': 'Cherry Capital Airport',
    'BZN': 'Bozeman Yellowstone International Airport',
    'JAC': 'Jackson Hole Airport',
    'PSP': 'Palm Springs International Airport',
    'HDN': 'Yampa Valley Regional Airport',
    'MTJ': 'Montrose Regional Airport',
    'BWI': 'Baltimore/Washington International Thurgood Marshall Airport',
    'SBN': 'South Bend International Airport',
    'ANC': 'Ted Stevens Anchorage International Airport',
    'MEM': 'Memphis International Airport',
    'BHM': 'Birmingham-Shuttlesworth International Airport',
    'LGA': 'LaGuardia Airport'
}

# Create a mapping dictionary for 'origin' to 'Origin Name' (airport names)
origin_name_mapping = {
    'JFK': 'John F. Kennedy International Airport',
    'EWR': 'Newark Liberty International Airport',
    'LGA': 'LaGuardia Airport'
}

# Replace missing values in 'Destination Name' using the destination_name_mapping
combined_data['Destination Name'] = combined_data['Destination Name'].fillna(combined_data['dest'].map(destination_name_mapping))

# Replace missing values in 'Origin Name' using the origin_name_mapping
combined_data['Origin Name'] = combined_data['Origin Name'].fillna(combined_data['origin'].map(origin_name_mapping))

combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport    10948
Destination City           0
Destination Country        0
Destination Name           0
Distance               10948
Origin Airport         10948
Origin City                0
Origin Country             0
Origin Name                0
Number of Airlines     10948
dtype: int64

In [161]:
# Replace missing values in 'Destination Airport' with the respective values from 'dest'
combined_data['Destination Airport'] = combined_data['Destination Airport'].fillna(combined_data['dest'])

# Replace missing values in 'Origin Airport' with the respective values from 'origin'
combined_data['Origin Airport'] = combined_data['Origin Airport'].fillna(combined_data['origin'])

combined_data.head(10)

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Number of Airlines
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,1.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,2.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,3.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,BQN,Aguadilla,Puerto Rico,Rafael Hernández Airport,NaN,JFK,New York,United States,John F. Kennedy International Airport,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,7.0
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,3.0
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,Foreign Corporation,AIRBUS INDUSTRIE,10/05/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,Corporation,CANADAIR,04/23/2004,CL-600-2B19,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,IAD,Washington,United States,Washington Dulles International Airport,True,LGA,New York,United States,La Guardia Airport,1.0
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,Corporation,AIRBUS,09/29/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,MCO,Orlando,United States,Orlando International Airport,True,JFK,New York,United States,John F Kennedy International Airport,4.0
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,LGA,New York,United States,La Guardia Airport,5.0

In [162]:
combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport        0
Destination City           0
Destination Country        0
Destination Name           0
Distance               10948
Origin Airport             0
Origin City                0
Origin Country             0
Origin Name                0
Number of Airlines     10948
dtype: int64

To replace the missing values in the `Number of Airlines` column with the number of airlines that fly to each Destination Airport, we can follow these steps:

* Count the Number of Airlines per Destination Airport: This will involve grouping the data by `Destination Airport` and counting the number of unique airlines (`carrier`).
* Use this information to fill missing values in Number of Airlines.

In [163]:
# Step 1: Group by 'Destination Airport' and count the number of unique carriers (airlines)
airlines_per_destination = combined_data.groupby('Destination Airport')['carrier'].nunique()

# Step 2: Create a mapping of 'Destination Airport' to the number of airlines
airlines_mapping = airlines_per_destination.to_dict()

airlines_mapping

{'ABQ': 1,
 'ACK': 1,
 'ALB': 1,
 'ANC': 1,
 'ATL': 7,
 'AUS': 6,
 'AVL': 2,
 'BDL': 2,
 'BGR': 2,
 'BHM': 1,
 'BNA': 5,
 'BOS': 7,
 'BQN': 2,
 'BTV': 3,
 'BUF': 4,
 'BUR': 1,
 'BWI': 4,
 'BZN': 1,
 'CAE': 2,
 'CAK': 1,
 'CHO': 1,
 'CHS': 4,
 'CLE': 5,
 'CLT': 7,
 'CMH': 3,
 'CRW': 1,
 'CVG': 4,
 'DAY': 2,
 'DCA': 6,
 'DEN': 5,
 'DFW': 4,
 'DSM': 2,
 'DTW': 6,
 'EGE': 2,
 'EYW': 1,
 'FLL': 4,
 'GRR': 2,
 'GSO': 2,
 'GSP': 2,
 'HDN': 1,
 'HNL': 2,
 'HOU': 2,
 'IAD': 6,
 'IAH': 2,
 'ILM': 1,
 'IND': 5,
 'JAC': 2,
 'JAX': 4,
 'LAS': 5,
 'LAX': 5,
 'LEX': 1,
 'LGA': 1,
 'LGB': 1,
 'MCI': 3,
 'MCO': 4,
 'MDW': 1,
 'MEM': 3,
 'MHT': 2,
 'MIA': 3,
 'MKE': 4,
 'MSN': 2,
 'MSP': 6,
 'MSY': 6,
 'MTJ': 1,
 'MVY': 2,
 'MYR': 1,
 'OAK': 1,
 'OKC': 1,
 'OMA': 3,
 'ORD': 7,
 'ORF': 3,
 'PBI': 5,
 'PDX': 3,
 'PHL': 5,
 'PHX': 5,
 'PIT': 6,
 'PSE': 1,
 'PSP': 1,
 'PVD': 1,
 'PWM': 3,
 'RDU': 5,
 'RIC': 2,
 'ROC': 3,
 'RSW': 4,
 'SAN': 4,
 'SAT': 3,
 'SAV': 1,
 'SBN': 1,
 'SDF': 3,
 'SEA': 5,
 'SFO': 5,
 'SJC': 2,
 'SJU': 4,
 'SLC': 2,
 'SMF': 1,
 'SNA': 1,
 'SRQ': 4,
 'STL': 6,
 'STT': 3,
 'SYR': 3,
 'TPA': 7,
 'TUL': 1,
 'TVC': 2,
 'TYS': 2,
 'XNA': 2}

In [164]:
combined_data['Number of Airlines'] = combined_data['Number of Airlines'].fillna(combined_data['Destination Airport'].map(airlines_mapping))

combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport        0
Destination City           0
Destination Country        0
Destination Name           0
Distance               10948
Origin Airport             0
Origin City                0
Origin Country             0
Origin Name                0
Number of Airlines         0
dtype: int64

In [165]:
combined_data.head(10)

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Number of Airlines
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,1.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,2.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,3.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,BQN,Aguadilla,Puerto Rico,Rafael Hernández Airport,NaN,JFK,New York,United States,John F. Kennedy International Airport,2.0
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,7.0
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,3.0
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,Foreign Corporation,AIRBUS INDUSTRIE,10/05/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,2.0
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,Corporation,CANADAIR,04/23/2004,CL-600-2B19,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,IAD,Washington,United States,Washington Dulles International Airport,True,LGA,New York,United States,La Guardia Airport,1.0
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,Corporation,AIRBUS,09/29/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,MCO,Orlando,United States,Orlando International Airport,True,JFK,New York,United States,John F Kennedy International Airport,4.0
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,ORD,Chicago,United States,Chicago O'Hare International Airport,True,LGA,New York,United States,La Guardia Airport,5.0

Finally removing some few columns. Renaming certain columns for better clarity.

In [166]:
# Step 1: Remove the columns 'Distance', 'Destination Airport', and 'Origin Airport'
combined_data = combined_data.drop(columns=['Distance', 'Destination Airport', 'Origin Airport'])

# Step 2: Rename 'year_x' to 'Flight Year' and 'year_y' to 'Manufacturing Year'
combined_data = combined_data.rename(columns={'year_x': 'Flight Year', 'year_y': 'Manufacturing Year'})

Creating a boolean `Delayed` column with `Yes` or `No` values based on if `arr_delay` > 0, then the flight was delayed. This column is going to be our target column for future machine learning models.

In [167]:
# Create a boolean column 'Delayed'
combined_data['Delayed'] = np.where(combined_data['arr_delay'] > 0, 'Yes', 'No')

## Final Cleaned Data.
Finally, after cleaning, transformations, reductions, quality checks, merging, we have our `combined_data` as the final cleaned data that can now be used for further EDA and answering our questions.

In [168]:
combined_data.head(10)

,Flight Year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,Manufacturing Year,Destination City,Destination Country,Destination Name,Origin City,Origin Country,Origin Name,Number of Airlines,Delayed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Houston,United States,George Bush Intercontinental Houston Airport,Newark,United States,Newark Liberty International Airport,1.0,Yes
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,Houston,United States,George Bush Intercontinental Houston Airport,New York,United States,La Guardia Airport,2.0,Yes
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,Miami,United States,Miami International Airport,New York,United States,John F Kennedy International Airport,3.0,Yes
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Aguadilla,Puerto Rico,Rafael Hernández Airport,New York,United States,John F. Kennedy International Airport,2.0,No
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,New York,United States,La Guardia Airport,7.0,No
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Chicago,United States,Chicago O'Hare International Airport,Newark,United States,Newark Liberty International Airport,3.0,Yes
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,Foreign Corporation,AIRBUS INDUSTRIE,10/05/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,Newark,United States,Newark Liberty International Airport,2.0,Yes
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,Corporation,CANADAIR,04/23/2004,CL-600-2B19,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,Washington,United States,Washington Dulles International Airport,New York,United States,La Guardia Airport,1.0,No
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,Corporation,AIRBUS,09/29/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,Orlando,United States,Orlando International Airport,New York,United States,John F Kennedy International Airport,4.0,No
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Chicago,United States,Chicago O'Hare International Airport,New York,United States,La Guardia Airport,5.0,Yes