In [176]:
import numpy as np
import pandas as pd
import matplotlib as plt
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [177]:
#loading the datasets

flight = pd.read_csv("/content/drive/MyDrive/Data-Mining/flights.csv")
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z

In [178]:
plane_data = pd.read_csv("/content/drive/MyDrive/Data-Mining/plane-data.csv")
plane_data.head()

,tailnum,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year
0,N050AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N051AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,N052AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N054AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N055AA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [179]:
flight_routes = pd.read_csv("/content/drive/MyDrive/Data-Mining/us_flight_routes.csv", encoding ="utf-16",delimiter='\t')
flight_routes.tail()

,Airport ID,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Buffer,Destination Airport ID,Destination Latitude,Destination Longitude,Destination Point,Distance (Miles),Makeline,Number of Airlines,Origin Airport ID,Origin Latitude,Origin Longitude,Origin Point
4959,3469,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,False,SFO,San Francisco,United States,San Francisco International Airport,Polygon,3682,33.6367,-84.428101,Point,2138.896563,LineString,11,3469,37.618999,-122.375000,Point
4960,3682,MIA,Miami,United States,Miami International Airport,True,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,Polygon,3576,25.7932,-80.290604,Point,594.601524,LineString,12,3682,33.636700,-84.428101,Point
4961,3576,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,MIA,Miami,United States,Miami International Airport,Polygon,3682,33.6367,-84.428101,Point,594.601524,LineString,12,3576,25.793200,-80.290604,Point
4962,3682,ORD,Chicago,United States,Chicago O'Hare International Airport,True,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,Polygon,3830,41.9786,-87.904800,Point,605.810275,LineString,19,3682,33.636700,-84.428101,Point
4963,3830,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,ORD,Chicago,United States,Chicago O'Hare International Airport,Polygon,3682,33.6367,-84.428101,Point,605.810275,LineString,20,3830,41.978600,-87.904800,Point

In [180]:
flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

In [181]:
flight.isna().sum()

year                 0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8713
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [182]:
plane_data.isna().sum()

tailnum            0
type             549
manufacturer     549
issue_date       550
model            549
status           549
aircraft_type    549
engine_type      552
year             694
dtype: int64

In [183]:
flight_routes.isna().sum()

Airport ID                0
Destination Airport       0
Destination City          0
Destination Country       0
Destination Name          0
Distance                  0
Origin Airport            0
Origin City               0
Origin Country            0
Origin Name               0
Buffer                    0
Destination Airport ID    0
Destination Latitude      0
Destination Longitude     0
Destination Point         0
Distance (Miles)          0
Makeline                  0
Number of Airlines        0
Origin Airport ID         0
Origin Latitude           0
Origin Longitude          0
Origin Point              0
dtype: int64

In [184]:
len(flight)

336776

In [185]:
len(plane_data)

5029

In [186]:
len(flight_routes)

4964

In [187]:

# Replace missing values in dep_time with sched_dep_time
flight.loc[flight['dep_time'].isna(), 'dep_time'] = flight['sched_dep_time']

# Replace missing values in arr_time with sched_arr_time
flight.loc[flight['arr_time'].isna(), 'arr_time'] = flight['sched_arr_time']

# Display the first few rows to check the result
flight.isna().sum()

year                 0
month                0
day                  0
dep_time             0
sched_dep_time       0
dep_delay         8255
arr_time             0
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [188]:
import pandas as pd

# Function to convert HHMM format to total minutes
def convert_to_minutes(time_col):
    # Handle NaN cases for dep_time (since it's float64, it could have NaNs)
    time_col = time_col.fillna(0).astype(int)

    # Extract hours and minutes from HHMM format
    hours = time_col // 100
    minutes = time_col % 100

    # Convert the time into total minutes
    return hours * 60 + minutes

# Convert dep_time and sched_dep_time to minutes
flight['dep_time_minutes'] = convert_to_minutes(flight['dep_time'])
flight['sched_dep_time_minutes'] = convert_to_minutes(flight['sched_dep_time'])

# Replace missing dep_delay values by calculating dep_time - sched_dep_time
flight.loc[flight['dep_delay'].isna(), 'dep_delay'] = flight['dep_time_minutes'] - flight['sched_dep_time_minutes']

# Convert arr_time and sched_arr_time to minutes
flight['arr_time_minutes'] = convert_to_minutes(flight['arr_time'])
flight['sched_arr_time_minutes'] = convert_to_minutes(flight['sched_arr_time'])

# Replace missing arr_delay values by calculating arr_time - sched_arr_time
flight.loc[flight['arr_delay'].isna(), 'arr_delay'] = flight['arr_time_minutes'] - flight['sched_arr_time_minutes']

# Drop the intermediate time columns if no longer needed
flight = flight.drop(columns=['dep_time_minutes', 'sched_dep_time_minutes', 'arr_time_minutes', 'sched_arr_time_minutes'])

# Display the updated flight dataframe
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z

In [189]:
flight.isna().sum()

year                 0
month                0
day                  0
dep_time             0
sched_dep_time       0
dep_delay            0
arr_time             0
sched_arr_time       0
arr_delay            0
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [190]:
flight['arr_time_minutes'] = convert_to_minutes(flight['arr_time'])
flight['dep_time_minutes'] = convert_to_minutes(flight['dep_time'])

# Replace missing air_time values by calculating arr_time - dep_time
flight.loc[flight['air_time'].isna(), 'air_time'] = flight['arr_time_minutes'] - flight['dep_time_minutes']

# If you need to handle cases where the flight crosses midnight (e.g., dep_time is 2300 and arr_time is 0100):
flight.loc[flight['air_time'] < 0, 'air_time'] += 24 * 60  # Add 24 hours in minutes to fix negative values

# Drop the intermediate time columns if no longer needed
flight = flight.drop(columns=['arr_time_minutes', 'dep_time_minutes'])

# Display the updated flight dataframe
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T05:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T05:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T05:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T05:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T06:00:00Z

In [191]:
flight.isna().sum()

year                 0
month                0
day                  0
dep_time             0
sched_dep_time       0
dep_delay            0
arr_time             0
sched_arr_time       0
arr_delay            0
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time             0
distance             0
hour                 0
minute               0
time_hour            0
dtype: int64

In [192]:
# Remove the 'time_hour' column from the flight dataframe
flight = flight.drop(columns=['time_hour'])

# Display the updated flight dataframe
flight.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0

In [193]:
# Perform left join on a common key, e.g., 'plane_id'
# Replace 'plane_id' with the actual column name common to both datasets
merged_data = pd.merge(flight, plane_data, how='left', on='tailnum')

# Display the first few rows of the merged dataset
merged_data.head()

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0

In [194]:
merged_data.isna().sum()

year_x                 0
month                  0
day                    0
dep_time               0
sched_dep_time         0
dep_delay              0
arr_time               0
sched_arr_time         0
arr_delay              0
carrier                0
flight                 0
tailnum             2512
origin                 0
dest                   0
air_time               0
distance               0
hour                   0
minute                 0
type              113992
manufacturer      113992
issue_date        114010
model             113992
status            113992
aircraft_type     113992
engine_type       113992
year_y            119780
dtype: int64

In [195]:
len(merged_data)

336776

"Not Available" - This will show that there are no missing values and you also don't have to loose any data points (in this case, any flights). When creating visualizations using these columns with "Not Available" values, we will just ignore the Not Available values.

In [196]:
# List of columns where missing values should be replaced with 'Not Available'
columns_to_fill = ['tailnum', 'type', 'manufacturer', 'issue_date', 'model', 'status', 'aircraft_type', 'engine_type', 'year_y']

# Replace missing values in these columns with 'Not Available'
merged_data[columns_to_fill] = merged_data[columns_to_fill].fillna("Not Available")

# Display the updated plane_data dataframe
merged_data.isna().sum()

year_x            0
month             0
day               0
dep_time          0
sched_dep_time    0
dep_delay         0
arr_time          0
sched_arr_time    0
arr_delay         0
carrier           0
flight            0
tailnum           0
origin            0
dest              0
air_time          0
distance          0
hour              0
minute            0
type              0
manufacturer      0
issue_date        0
model             0
status            0
aircraft_type     0
engine_type       0
year_y            0
dtype: int64

In [197]:
flight_routes.columns

Index(['Airport ID', 'Destination Airport', 'Destination City',
       'Destination Country', 'Destination Name', 'Distance', 'Origin Airport',
       'Origin City', 'Origin Country', 'Origin Name', 'Buffer',
       'Destination Airport ID', 'Destination Latitude',
       'Destination Longitude', 'Destination Point ', 'Distance (Miles)',
       'Makeline', 'Number of Airlines', 'Origin Airport ID',
       'Origin Latitude', 'Origin Longitude', 'Origin Point'],
      dtype='object')

In [198]:
merged_data.columns

Index(['year_x', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'type', 'manufacturer', 'issue_date', 'model', 'status',
       'aircraft_type', 'engine_type', 'year_y'],
      dtype='object')

In [199]:
# Merge the two datasets on origin and destination airport codes
combined_data = pd.merge(merged_data, flight_routes,
                         how='left',
                         left_on=['origin', 'dest'],
                         right_on=['Origin Airport', 'Destination Airport'])

# Display the first few rows of the combined dataset
combined_data.head()

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Airport ID,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Buffer,Destination Airport ID,Destination Latitude,Destination Longitude,Destination Point,Distance (Miles),Makeline,Number of Airlines,Origin Airport ID,Origin Latitude,Origin Longitude,Origin Point
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3494.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3550.0,29.9844,-95.341400,Point,1399.812458,LineString,1.0,3494.0,40.692501,-74.168701,Point
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,3697.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,Polygon,3550.0,29.9844,-95.341400,Point,1416.367401,LineString,2.0,3697.0,40.777199,-73.872597,Point
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,3797.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,Polygon,3576.0,25.7932,-80.290604,Point,1089.635644,LineString,3.0,3797.0,40.639801,-73.778900,Point
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,3697.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3682.0,33.6367,-84.428101,Point,761.521651,LineString,7.0,3697.0,40.777199,-73.872597,Point

In [200]:
# Set display options to show all columns
pd.set_option('display.max_columns', None)

# Now, when you display the DataFrame, it will show all columns
combined_data.head(10)

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Airport ID,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Buffer,Destination Airport ID,Destination Latitude,Destination Longitude,Destination Point,Distance (Miles),Makeline,Number of Airlines,Origin Airport ID,Origin Latitude,Origin Longitude,Origin Point
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3494.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3550.0,29.984400,-95.341400,Point,1399.812458,LineString,1.0,3494.0,40.692501,-74.168701,Point
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,3697.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,Polygon,3550.0,29.984400,-95.341400,Point,1416.367401,LineString,2.0,3697.0,40.777199,-73.872597,Point
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,3797.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,Polygon,3576.0,25.793200,-80.290604,Point,1089.635644,LineString,3.0,3797.0,40.639801,-73.778900,Point
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,3697.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3682.0,33.636700,-84.428101,Point,761.521651,LineString,7.0,3697.0,40.777199,-73.872597,Point
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3494.0,ORD,Chicago,United States,Chicago O'Hare International Airport,True,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3830.0,41.978600,-87.904800,Point,719.156918,LineString,3.0,3494.0,40.692501,-74.168701,Point
6,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,Foreign Corporation,AIRBUS INDUSTRIE,10/05/2000,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,2000.0,3494.0,FLL,Fort Lauderdale,United States,Fort Lauderdale Hollywood International Airport,False,EWR,Newark,United States,Newark Liberty International Airport,Polygon,3533.0,26.072599,-80.152702,Point,1064.607704,LineString,2.0,3494.0,40.692501,-74.168701,Point
7,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,Corporation,CANADAIR,04/23/2004,CL-600-2B19,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1998.0,3697.0,IAD,Washington,United States,Washington Dulles International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3714.0,38.944500,-77.455803,Point,228.624105,LineString,1.0,3697.0,40.777199,-73.872597,Point
8,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,Corporation,AIRBUS,09/29/2004,A320-232,Valid,Fixed Wing Multi-Engine,Turbo-Fan,2004.0,3797.0,MCO,Orlando,United States,Orlando International Airport,True,JFK,New York,United States,John F Kennedy International Airport,Polygon,3878.0,28.429399,-81.308998,Point,944.001760,LineString,4.0,3797.0,40.639801,-73.778900,Point
9,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,3697.0,ORD,Chicago,United States,Chicago O'Hare International Airport,True,LGA,New York,United States,La Guardia Airport,Polygon,3830.0,41.978600,-87.904800,Point,733.245012,LineString,5.0,3697.0,40.777199,-73.872597,Point

In [201]:
combined_data.columns

Index(['year_x', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'type', 'manufacturer', 'issue_date', 'model', 'status',
       'aircraft_type', 'engine_type', 'year_y', 'Airport ID',
       'Destination Airport', 'Destination City', 'Destination Country',
       'Destination Name', 'Distance', 'Origin Airport', 'Origin City',
       'Origin Country', 'Origin Name', 'Buffer', 'Destination Airport ID',
       'Destination Latitude', 'Destination Longitude', 'Destination Point ',
       'Distance (Miles)', 'Makeline', 'Number of Airlines',
       'Origin Airport ID', 'Origin Latitude', 'Origin Longitude',
       'Origin Point'],
      dtype='object')

In [202]:
# Remove the 'time_hour' column from the flight dataframe
combined_data = combined_data.drop(columns=['Buffer','Makeline','Origin Latitude','Origin Longitude','Origin Point','Destination Airport ID',
                                            'Destination Latitude', 'Destination Longitude','Destination Point ','Origin Point',
                                            'Origin Point','Distance (Miles)','Origin Airport ID','Airport ID'])

# Display the updated flight dataframe
combined_data.head()

,year_x,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,type,manufacturer,issue_date,model,status,aircraft_type,engine_type,year_y,Destination Airport,Destination City,Destination Country,Destination Name,Distance,Origin Airport,Origin City,Origin Country,Origin Name,Number of Airlines
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,EWR,Newark,United States,Newark Liberty International Airport,1.0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,Corporation,BOEING,07/31/1998,737-824,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1998.0,IAH,Houston,United States,George Bush Intercontinental Houston Airport,False,LGA,New York,United States,La Guardia Airport,2.0
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,Corporation,BOEING,12/14/1999,757-223,Valid,Fixed Wing Multi-Engine,Turbo-Fan,1990.0,MIA,Miami,United States,Miami International Airport,False,JFK,New York,United States,John F Kennedy International Airport,3.0
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,Corporation,BOEING,06/26/1991,757-232,Valid,Fixed Wing Multi-Engine,Turbo-Jet,1991.0,ATL,Atlanta,United States,Hartsfield Jackson Atlanta International Airport,True,LGA,New York,United States,La Guardia Airport,7.0

In [203]:
combined_data.isna().sum()

year_x                     0
month                      0
day                        0
dep_time                   0
sched_dep_time             0
dep_delay                  0
arr_time                   0
sched_arr_time             0
arr_delay                  0
carrier                    0
flight                     0
tailnum                    0
origin                     0
dest                       0
air_time                   0
distance                   0
hour                       0
minute                     0
type                       0
manufacturer               0
issue_date                 0
model                      0
status                     0
aircraft_type              0
engine_type                0
year_y                     0
Destination Airport    10948
Destination City       10948
Destination Country    10948
Destination Name       10948
Distance               10948
Origin Airport         10948
Origin City            10948
Origin Country         10948
Origin Name            10948
Number of Airlines     10948
dtype: int64